insert into authors (id, first_name, last_name) values (1, 'Monah', 'Arends');
insert into authors (id, first_name, last_name) values (2, 'Sula', 'Gainsford');
insert into authors (id, first_name, last_name) values (3, 'Joanie', 'Strutley');
insert into authors (id, first_name, last_name) values (4, 'Leigh', 'Spillett');
insert into authors (id, first_name, last_name) values (5, 'Judie', 'Orford');
insert into authors (id, first_name, last_name) values (6, 'Karel', 'Romanski');
insert into authors (id, first_name, last_name) values (7, 'Edlin', 'Cecely');
insert into authors (id, first_name, last_name) values (8, 'Roarke', 'Jakubowski');
insert into authors (id, first_name, last_name) values (9, 'Falito', 'Rowbottam');
insert into authors (id, first_name, last_name) values (10, 'Elysia', 'Stuchberry');
insert into authors (id, first_name, last_name) values (11, 'Kellsie', 'Sivyer');
insert into authors (id, first_name, last_name) values (12, 'Merrielle', 'Thorsen');
insert into authors (id, first_name, last_name) values (13, 'Pollyanna', 'Orleton');
insert into authors (id, first_name, last_name) values (14, 'Cam', 'Rekes');
insert into authors (id, first_name, last_name) values (15, 'Roxy', 'McCrackan');
insert into authors (id, first_name, last_name) values (16, 'Aigneis', 'Boother');
insert into authors (id, first_name, last_name) values (17, 'Laurice', 'Jesper');
insert into authors (id, first_name, last_name) values (18, 'Ethelred', 'Harfleet');
insert into authors (id, first_name, last_name) values (19, 'Ardella', 'Espadate');
insert into authors (id, first_name, last_name) values (20, 'Marietta', 'Ryley');
insert into authors (id, first_name, last_name) values (21, 'Leyla', 'Hearn');

insert into books (id, price, price_old, title, author_id) values (1, 1020, 1348, 'Prodder', 6);
insert into books (id, price, price_old, title, author_id) values (2, 1423, 3881, 'Trippledex', 16);
insert into books (id, price, price_old, title, author_id) values (3, 2622, 2208, 'Home Ing', 10);
insert into books (id, price, price_old, title, author_id) values (4, 2532, 2002, 'Fintone', 7);
insert into books (id, price, price_old, title, author_id) values (5, 1854, 1015, 'Lotstring', 12);
insert into books (id, price, price_old, title, author_id) values (6, 2383, 1625, 'Konklux', 12);
insert into books (id, price, price_old, title, author_id) values (7, 507, 1130, 'Konklab', 8);
insert into books (id, price, price_old, title, author_id) values (8, 1475, 1634, 'Bytecard', 2);
insert into books (id, price, price_old, title, author_id) values (9, 2541, 3594, 'Transcof', 8);
insert into books (id, price, price_old, title, author_id) values (10, 2162, 2385, 'Sub-Ex', 2);
insert into books (id, price, price_old, title, author_id) values (11, 1857, 3918, 'Biodex', 20);
insert into books (id, price, price_old, title, author_id) values (12, 1067, 1715, 'Temp', 12);
insert into books (id, price, price_old, title, author_id) values (13, 1164, 2237, 'Bigtax', 8);
insert into books (id, price, price_old, title, author_id) values (14, 2109, 3519, 'Greenlam', 9);
insert into books (id, price, price_old, title, author_id) values (15, 629, 2813, 'Zoolab', 8);
insert into books (id, price, price_old, title, author_id) values (16, 2963, 3713, 'Sub-Ex', 5);
insert into books (id, price, price_old, title, author_id) values (17, 643, 1437, 'Voltsillam', 10);
insert into books (id, price, price_old, title, author_id) values (18, 2684, 1678, 'Aerified', 5);
insert into books (id, price, price_old, title, author_id) values (19, 772, 3033, 'It', 18);
insert into books (id, price, price_old, title, author_id) values (20, 725, 3544, 'Alphazap', 1);
insert into books (id, price, price_old, title, author_id) values (21, 717, 3205, 'Bytecard', 5);

